apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ayb4e0eh3-go 
  janus-idp.io/tekton: ayb4e0eh3-go
  backstage.io/kubernetes-id: ayb4e0eh3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ayb4e0eh3-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml